version: "3.9"

services:
  backend:
    build: .
    container_name: feedforward-backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
